# Generated by Django 6.0.7 on 2026-07-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('carrier', models.CharField(max_length=255)),
                ('tracking_id', models.CharField(max_length=50)),
                ('package_type', models.CharField(max_length=20)),
                ('shipment_type', models.CharField(max_length=20)),
                ('shipment_mode', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_mode', models.CharField(max_length=20)),
                ('total_freight', models.DecimalField(decimal_places=2, help_text='Shipping cost', max_digits=12)),
                ('total_weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovementLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_locations', to='public.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_address', models.TextField()),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_address', models.TextField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_contacts', to='public.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('latest_message', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=255)),
                ('movement_status', models.CharField(max_length=50)),
                ('expected_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='public.shipment')),
            ],
        ),
    ]
