# Generated by Django 6.0.7 on 2026-07-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_shipment_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='goods_image',
            field=models.URLField(blank=True, help_text='URL to an image of the goods', max_length=500, null=True),
        ),
    ]
