# Generated by Django 6.0.7 on 2026-07-30 19:50

import json

from django.db import migrations, models


def normalize_goods_image_to_list(apps, schema_editor):
    Shipment = apps.get_model('public', 'Shipment')
    for shipment in Shipment.objects.all():
        value = shipment.goods_image
        if value in (None, ''):
            shipment.goods_image = []
        elif isinstance(value, str):
            shipment.goods_image = [value]
        else:
            shipment.goods_image = value
        shipment.save(update_fields=['goods_image'])


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_shipment_goods_image'),
    ]

    operations = [
        migrations.RunPython(normalize_goods_image_to_list, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shipment',
            name='goods_image',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for the goods', null=True),
        ),
    ]
