# Generated by Django 6.0.7 on 2026-07-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_movementlocation_latitude_movementlocation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='map_movement',
            field=models.BooleanField(default=False, help_text="Indicates if the shipment's movement should be tracked in real time in FE"),
        ),
    ]
