# Generated by Django 6.0.7 on 2026-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_shipment_map_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_wallet', models.BooleanField(default=False)),
                ('coin', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
